### ISSUE TITLE
Max Score is NaN in reports

### ISSUE THREAD

**Issue by brianberlin** [rewoo/onsite-seo#1]
Thanks for open sourcing this project. I've been looking for something focused with on page seo for a while now and this looks great. And in javascript which is even cooler.

First look, I found an issue with the scoring. Not sure if I overlooked something or if I need to setup something but I see in the report.html "Score: 1.00 of NaN" throughout. 

I took a look this morning to start trying to get an understanding for the code and found that max is not set in fns objects when getMaxScoreOfRatings is run here: https://github.com/rewoo/onsite-seo/blob/master/lib/ratings.js#L173 

It is asked for here: https://github.com/rewoo/onsite-seo/blob/master/lib/report.js#L31

I tried to track down where fns comes from, but honestly, I'm not really sure about how these scores work so I'm just gonna report it for now. Perhaps, I'll look further later today.

**Comment by rewoo** [comment]
Thanks a lot for pointing this error. With the bug fix your static report should work again. We recommend to use the javascript version for more flexibility.

The max value was a relict of previous scoring. Now the scores are normalized to 0.0 - 1.0 with a weight. This gives a greater flexibility.
